### ISSUE TITLE
install error on tei-pub packages

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/generator-exist#67]
the app seems to run fine though
short
```
Error found while processing repo.xml: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: console:log [at line 67, column 1] 
```

long
```
2018-07-19 18:38:36,518 [qtp554299447-209] WARN  (LuceneConfig.java [parseConfig]:311) - Invalid lucene configuration element: Lucene index configuration error: Illegal QName: starts or ends with a ':'. QName is invalid: ILLEGAL_FORMAT 
2018-07-19 18:38:39,565 [qtp554299447-209] ERROR (Deploy.java [installAndDeployFromDb]:216) - Error found while processing repo.xml: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: console:log [at line 67, column 1]
 
org.expath.pkg.repo.PackageException: Error found while processing repo.xml: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: console:log [at line 67, column 1]

	at org.exist.repo.Deployment.deploy(Deployment.java:470) ~[exist.jar:4.2.1]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:282) ~[exist.jar:4.2.1]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:164) ~[exist.jar:4.2.1]
	at org.exist.xquery.modules.expathrepo.Deploy.installAndDeployFromDb(Deploy.java:214) [exist-modules.jar:4.2.1]
	at org.exist.xquery.modules.expathrepo.Deploy.eval(Deploy.java:170) [exist-modules.jar:4.2.1]
	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) [exist.jar:4.2.1]
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:99) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:100) [exist.jar:4.2.1]
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:162) [exist.jar:4.2.1]
	at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:74) [exist.jar:4.2.1]
	at org.exist.xquery.Atomize.eval(Atomize.java:67) [exist.jar:4.2.1]
	at org.exist.xquery.DynamicTypeCheck.eval(DynamicTypeCheck.java:61) [exist.jar:4.2.1]
	at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:302) [exist.jar:4.2.1]
	at org.exist.xquery.FunctionCall.eval(FunctionCall.java:223) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:99) [exist.jar:4.2.1]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:4.2.1]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:4.2.1]
	at org.exist.xquery.TryCatchExpression.eval(TryCatchExpression.java:142) [exist.jar:4.2.1]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:4.2.1]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:4.2.1]
	at org.exist.xquery.EnclosedExpr.eval(EnclosedExpr.java:85) [exist.jar:4.2.1]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:4.2.1]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:4.2.1]
	at org.exist.xquery.ElementConstructor.eval(ElementConstructor.java:329) [exist.jar:4.2.1]
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:100) [exist.jar:4.2.1]
	at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:162) [exist.jar:4.2.1]
	at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:302) [exist.jar:4.2.1]
	at org.exist.xquery.FunctionCall.eval(FunctionCall.java:223) [exist.jar:4.2.1]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:4.2.1]
	at org.exist.xquery.value.FunctionReference.eval(FunctionReference.java:82) [exist.jar:4.2.1]
	at org.exist.xquery.DynamicFunctionCall.eval(DynamicFunctionCall.java:76) [exist.jar:4.2.1]
	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:100) [exist.jar:4.2.1]
	at org.exist.xquery.UserDefinedFunction.eval(UserDefinedFunction.java:162) [exist.jar:4.2.1]
	at org.exist.xquery.FunctionCall.evalFunction(FunctionCall.java:302) [exist.jar:4.2.1]
	at org.exist.xquery.FunctionCall.eval(FunctionCall.java:223) [exist.jar:4.2.1]
	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:4.2.1]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:4.2.1]
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:4.2.1]
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:4.2.1]
	at org.exist.xquery.XQuery.execute(XQuery.java:261) [exist.jar:4.2.1]
	at org.exist.xquery.XQuery.execute(XQuery.java:185) [exist.jar:4.2.1]
	at org.exist.http.RESTServer.executeXQuery(RESTServer.java:1533) [exist-optional.jar:4.2.1]
	at org.exist.http.RESTServer.doPost(RESTServer.java:698) [exist-optional.jar:4.2.1]
	at org.exist.http.servlets.EXistServlet.doPost(EXistServlet.java:452) [exist-optional.jar:4.2.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [servlet-api-3.1.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:163) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:51) [exist-optional.jar:4.2.1]
	at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:524) [exist-optional.jar:4.2.1]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:343) [exist-optional.jar:4.2.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171) [betterform-exist-5.1-SNAPSHOT-20160615.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524) [jetty-security-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:674) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.Server.handle(Server.java:531) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.exist.xquery.StaticXQueryException: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: console:log [at line 67, column 1]

	at org.exist.xquery.XQuery.compile(XQuery.java:115) ~[exist.jar:4.2.1]
	at org.exist.xquery.XQuery.compile(XQuery.java:79) ~[exist.jar:4.2.1]
	at org.exist.xquery.XQuery.compile(XQuery.java:71) ~[exist.jar:4.2.1]
	at org.exist.repo.Deployment.runQuery(Deployment.java:683) ~[exist.jar:4.2.1]
	at org.exist.repo.Deployment.deploy(Deployment.java:454) ~[exist.jar:4.2.1]
	... 118 more
2018-07-19 18:38:40,414 [qtp554299447-202] INFO  (LogFunction.java [writeLog]:199) - (Line: 115 /db/apps/packageservice/modules/packages.xqm) user: guest 
```

**Comment by duncdrum** [comment]
on-hold until work on #114 get going
